# Makefile.in generated by automake 1.11.1 from Makefile.am.
# src/pulsar/TwoSpect/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/lalapps
pkgincludedir = $(includedir)/lalapps
pkglibdir = $(libdir)/lalapps
pkglibexecdir = $(libexecdir)/lalapps
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = lalapps_TwoSpect$(EXEEXT)
EXTRA_PROGRAMS = skygridsetup$(EXEEXT) compareCandidates$(EXEEXT) \
	KSKtests$(EXEEXT)
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/gnuscripts/vcsID.common
subdir = src/pulsar/TwoSpect
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/gnuscripts/ax_mpi.m4 \
	$(top_srcdir)/gnuscripts/lalapps.m4 \
	$(top_srcdir)/gnuscripts/lalsuite_build.m4 \
	$(top_srcdir)/gnuscripts/lalsuite_gccflags.m4 \
	$(top_srcdir)/gnuscripts/libtool.m4 \
	$(top_srcdir)/gnuscripts/ltoptions.m4 \
	$(top_srcdir)/gnuscripts/ltsugar.m4 \
	$(top_srcdir)/gnuscripts/ltversion.m4 \
	$(top_srcdir)/gnuscripts/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/gnuscripts/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_KSKtests_OBJECTS = cmdline.$(OBJEXT) antenna.$(OBJEXT) \
	KSKtests.$(OBJEXT)
KSKtests_OBJECTS = $(am_KSKtests_OBJECTS)
KSKtests_LDADD = $(LDADD)
KSKtests_DEPENDENCIES = $(top_builddir)/src/lalapps/liblalapps.la
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am_compareCandidates_OBJECTS = compareCandidates.$(OBJEXT)
compareCandidates_OBJECTS = $(am_compareCandidates_OBJECTS)
compareCandidates_LDADD = $(LDADD)
compareCandidates_DEPENDENCIES =  \
	$(top_builddir)/src/lalapps/liblalapps.la
am_lalapps_TwoSpect_OBJECTS = cmdline.$(OBJEXT) statistics.$(OBJEXT) \
	fastchisqinv.$(OBJEXT) IHS.$(OBJEXT) candidates.$(OBJEXT) \
	templates.$(OBJEXT) antenna.$(OBJEXT) vectormath.$(OBJEXT) \
	cdfwchisq.$(OBJEXT) upperlimits.$(OBJEXT) TwoSpect.$(OBJEXT)
lalapps_TwoSpect_OBJECTS = $(am_lalapps_TwoSpect_OBJECTS)
lalapps_TwoSpect_LDADD = $(LDADD)
lalapps_TwoSpect_DEPENDENCIES =  \
	$(top_builddir)/src/lalapps/liblalapps.la
am_skygridsetup_OBJECTS = skygridsetup.$(OBJEXT) \
	cmdline_skygridsetup.$(OBJEXT) antenna.$(OBJEXT)
skygridsetup_OBJECTS = $(am_skygridsetup_OBJECTS)
skygridsetup_LDADD = $(LDADD)
skygridsetup_DEPENDENCIES = $(top_builddir)/src/lalapps/liblalapps.la
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/gnuscripts/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(KSKtests_SOURCES) $(compareCandidates_SOURCES) \
	$(lalapps_TwoSpect_SOURCES) $(skygridsetup_SOURCES)
DIST_SOURCES = $(KSKtests_SOURCES) $(compareCandidates_SOURCES) \
	$(lalapps_TwoSpect_SOURCES) $(skygridsetup_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run tar
AM_DEFAULT_VERBOSITY = 0
AM_LDFLAGS =  -all-static
AR = ar
AUTOCONF = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run autoconf
AUTOHEADER = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run autoheader
AUTOMAKE = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run automake-1.11
AWK = gawk
BIBTEX = bibtex
BOINC_PREFIX = 
CC = condor_compile gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFITSIO_CFLAGS = 
CFITSIO_LIBS = 
CFLAGS = -g -O2 -g3 -Wall -W -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -Wnested-externs -Wno-format-zero-length -fno-strict-aliasing -Wno-unused-result
CLANG_CC = 
CLANG_CXX = 
CONDOR_COMPILE = condor_compile
CPP = gcc -std=gnu99 -E
CPPFLAGS =          -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalframe/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalburst/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalinspiral/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalpulsar/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -std=gnu99 -I/home/grant.meadors/master/opt/lscsoft/lalinference/include -I/home/grant.meadors/master/opt/lscsoft/lalpulsar/include -I/home/grant.meadors/master/opt/lscsoft/lalinspiral/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include   -I/home/grant.meadors/master/opt/lscsoft/lalstochastic/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
CUDA_CPPFLAGS = 
CUDA_LIBS = 
CXX = 
CXXCPP = 
CXXDEPMODE = 
CXXFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DISTCHECK_CONFIGURE_FLAGS =  '--enable-condor' 'PKG_CONFIG_PATH=/home/grant.meadors/master/opt/lscsoft/lalinference/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalstochastic/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalburst/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalframe/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lal/lib/pkgconfig'
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
DVIPS = dvips
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FFTW3_CFLAGS =  
FFTW3_LIBS = -lfftw3 -lfftw3f -lm  
FGREP = /bin/grep -F
FRAME_CFLAGS =  
FRAME_LIBS = -lm -lFrame  
GENERATE_VCS_INFO = $(PYTHON) $(top_srcdir)/../gnuscripts/generate_vcs_info.py --git-path='$(GIT)' $(genvcsinfo_$(V))
GIT = /usr/bin/git
GREP = /bin/grep
GSL_CFLAGS =  
GSL_LIBS = -lgsl -lgslcblas -lm  
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LALBURST_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalburst/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALBURST_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalburst/share/lalburst
LALBURST_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalburst/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalburst -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALFRAME_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalframe/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALFRAME_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalframe/share/lalframe
LALFRAME_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalframe/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalframe -llal -lFrame -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALINFERENCE_CFLAGS = -std=gnu99 -I/home/grant.meadors/master/opt/lscsoft/lalinference/include -I/home/grant.meadors/master/opt/lscsoft/lalpulsar/include -I/home/grant.meadors/master/opt/lscsoft/lalinspiral/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALINFERENCE_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalinference/share/lalinference
LALINFERENCE_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalinference/lib -L/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib -L/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalinference -llalinspiral -llalpulsar -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALINSPIRAL_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalinspiral/include -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALINSPIRAL_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalinspiral/share/lalinspiral
LALINSPIRAL_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalinspiral -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALMETAIO_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALMETAIO_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalmetaio/share/lalmetaio
LALMETAIO_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalmetaio -llal -lmetaio -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALPULSAR_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalpulsar/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALPULSAR_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalpulsar/share/lalpulsar
LALPULSAR_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalpulsar -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALSIMULATION_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalsimulation/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALSIMULATION_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalsimulation/share/lalsimulation
LALSIMULATION_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalsimulation -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALSTOCHASTIC_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lalstochastic/include -I/home/grant.meadors/master/opt/lscsoft/lalmetaio/include -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALSTOCHASTIC_DATADIR = /home/grant.meadors/master/opt/lscsoft/lalstochastic/share/lalstochastic
LALSTOCHASTIC_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lalstochastic/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalstochastic -llalmetaio -llal -lmetaio -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALSUITE_BUILD = 
LALSUITE_SUBDIRS = 
LALSUPPORT_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LALSUPPORT_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llalsupport -lz -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LALXML_CFLAGS = 
LALXML_DATADIR = 
LALXML_LIBS = 
LAL_CFLAGS = -I/home/grant.meadors/master/opt/lscsoft/lal/include  
LAL_DATADIR = /home/grant.meadors/master/opt/lscsoft/lal/share/lal
LAL_LIBS = -L/home/grant.meadors/master/opt/lscsoft/lal/lib -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm  
LATEX = pdflatex
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS =  -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalframe/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalburst/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalinference/lib -L/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib -L/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib -L/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib -L/home/grant.meadors/master/opt/lscsoft/lalstochastic/lib -L/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib -L/home/grant.meadors/master/opt/lscsoft/lal/lib
LIBOBJS = 
LIBS = -lfftw3 -lfftw3f -lgsl -lgslcblas -lgsl -lgslcblas -lm   -lz -lm  -lfftw3 -lfftw3f -lm   -lm -lFrame   -lmetaio   -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalsupport -lz -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalframe -llal -lFrame -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalmetaio -llal -lmetaio -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalsimulation -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalburst -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalinspiral -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalpulsar -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalinference -llalinspiral -llalpulsar -llalmetaio -llalsimulation -lmetaio -llal -lgsl -lgslcblas -lfftw3 -lfftw3f -lm -llalstochastic -llalmetaio -llal -lmetaio -lgsl -lgslcblas -lfftw3 -lfftw3f -lm
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBXML2_CFLAGS = 
LIBXML2_LIBS = 
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/missing --run makeinfo
MANIFEST_TOOL = :
METAIO_CFLAGS =  
METAIO_LIBS = -lmetaio  
MKDIR_P = /bin/mkdir -p
MKIND = makeindex
MPICC = 
MPILIBS = 
NIGHTLY_VERSION = 
NM = /usr/bin/nm -B
NMEDIT = 
NVCC = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = lalapps
PACKAGE_BUGREPORT = lal-discuss@ligo.org
PACKAGE_NAME = lalapps
PACKAGE_STRING = lalapps 6.13.1.1
PACKAGE_TARNAME = lalapps
PACKAGE_URL = 
PACKAGE_VERSION = 6.13.1.1
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /home/grant.meadors/master/opt/lscsoft/lalinference/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalpulsar/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalstochastic/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalinspiral/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalburst/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalsimulation/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalmetaio/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lalframe/lib/pkgconfig:/home/grant.meadors/master/opt/lscsoft/lal/lib/pkgconfig
PSS_CFLAGS = 
PSS_LIBS = 
PYTHON = /usr/bin/python
PYTHON_EXEC_PREFIX = ${exec_prefix}
PYTHON_PLATFORM = linux2
PYTHON_PREFIX = ${prefix}
PYTHON_VERSION = 2.6
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
SW_VERS = 
VERSION = 6.13.1.1
abs_builddir = /home/grant.meadors/src/lscsoft/lalsuite/lalapps/src/pulsar/TwoSpect
abs_srcdir = /home/grant.meadors/src/lscsoft/lalsuite/lalapps/src/pulsar/TwoSpect
abs_top_builddir = /home/grant.meadors/src/lscsoft/lalsuite/lalapps
abs_top_srcdir = /home/grant.meadors/src/lscsoft/lalsuite/lalapps
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = 
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
genvcsinfo_ = $(genvcsinfo_$(AM_DEFAULT_VERBOSITY))
genvcsinfo_0 = --am-v-gen='$(AM_V_GEN)'
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/grant.meadors/src/lscsoft/lalsuite/lalapps/gnuscripts/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgpyexecdir = ${pyexecdir}/lalapps
pkgpythondir = ${pkgpyexecdir}
prefix = /home/grant.meadors/master/opt/lscsoft/lalapps
program_transform_name = s,x,x,
psdir = ${docdir}
pyexecdir = ${exec_prefix}/lib/python2.6/site-packages
pythondir = ${prefix}/lib/python2.6/site-packages
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../../
top_builddir = ../../..
top_srcdir = ../../..
AM_CPPFLAGS = -I$(top_srcdir)/src -I$(top_srcdir)/src/lalapps -DPKG_DATA_DIR='"$(pkgdatadir)/"'
LDADD = $(top_builddir)/src/lalapps/liblalapps.la
lalapps_TwoSpect_SOURCES = cmdline.c statistics.c fastchisqinv.c IHS.c candidates.c templates.c antenna.c \
                           vectormath.c cdfwchisq.c upperlimits.c TwoSpect.c \
			   cmdline.h TwoSpectTypes.h statistics.h fastchisqinv.h IHS.h candidates.h templates.h \
                           antenna.h vectormath.h cdfwchisq.h upperlimits.h TwoSpect.h

skygridsetup_SOURCES = helperprograms/skygridsetup.c helperprograms/cmdline_skygridsetup.c antenna.c \
                       helperprograms/cmdline_skygridsetup.h antenna.h

compareCandidates_SOURCES = helperprograms/compareCandidates.c
KSKtests_SOURCES = cmdline.c antenna.c helperprograms/KSKtests.c \
		   cmdline.h TwoSpectTypes.h antenna.h

BUILT_SOURCES = vcsID
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/gnuscripts/vcsID.common $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/pulsar/TwoSpect/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/pulsar/TwoSpect/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
KSKtests$(EXEEXT): $(KSKtests_OBJECTS) $(KSKtests_DEPENDENCIES) 
	@rm -f KSKtests$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(KSKtests_OBJECTS) $(KSKtests_LDADD) $(LIBS)
compareCandidates$(EXEEXT): $(compareCandidates_OBJECTS) $(compareCandidates_DEPENDENCIES) 
	@rm -f compareCandidates$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(compareCandidates_OBJECTS) $(compareCandidates_LDADD) $(LIBS)
lalapps_TwoSpect$(EXEEXT): $(lalapps_TwoSpect_OBJECTS) $(lalapps_TwoSpect_DEPENDENCIES) 
	@rm -f lalapps_TwoSpect$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(lalapps_TwoSpect_OBJECTS) $(lalapps_TwoSpect_LDADD) $(LIBS)
skygridsetup$(EXEEXT): $(skygridsetup_OBJECTS) $(skygridsetup_DEPENDENCIES) 
	@rm -f skygridsetup$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(skygridsetup_OBJECTS) $(skygridsetup_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/IHS.Po
include ./$(DEPDIR)/KSKtests.Po
include ./$(DEPDIR)/TwoSpect.Po
include ./$(DEPDIR)/antenna.Po
include ./$(DEPDIR)/candidates.Po
include ./$(DEPDIR)/cdfwchisq.Po
include ./$(DEPDIR)/cmdline.Po
include ./$(DEPDIR)/cmdline_skygridsetup.Po
include ./$(DEPDIR)/compareCandidates.Po
include ./$(DEPDIR)/fastchisqinv.Po
include ./$(DEPDIR)/skygridsetup.Po
include ./$(DEPDIR)/statistics.Po
include ./$(DEPDIR)/templates.Po
include ./$(DEPDIR)/upperlimits.Po
include ./$(DEPDIR)/vectormath.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

KSKtests.o: helperprograms/KSKtests.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT KSKtests.o -MD -MP -MF $(DEPDIR)/KSKtests.Tpo -c -o KSKtests.o `test -f 'helperprograms/KSKtests.c' || echo '$(srcdir)/'`helperprograms/KSKtests.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/KSKtests.Tpo $(DEPDIR)/KSKtests.Po
#	$(AM_V_CC) \
#	source='helperprograms/KSKtests.c' object='KSKtests.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o KSKtests.o `test -f 'helperprograms/KSKtests.c' || echo '$(srcdir)/'`helperprograms/KSKtests.c

KSKtests.obj: helperprograms/KSKtests.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT KSKtests.obj -MD -MP -MF $(DEPDIR)/KSKtests.Tpo -c -o KSKtests.obj `if test -f 'helperprograms/KSKtests.c'; then $(CYGPATH_W) 'helperprograms/KSKtests.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/KSKtests.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/KSKtests.Tpo $(DEPDIR)/KSKtests.Po
#	$(AM_V_CC) \
#	source='helperprograms/KSKtests.c' object='KSKtests.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o KSKtests.obj `if test -f 'helperprograms/KSKtests.c'; then $(CYGPATH_W) 'helperprograms/KSKtests.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/KSKtests.c'; fi`

compareCandidates.o: helperprograms/compareCandidates.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT compareCandidates.o -MD -MP -MF $(DEPDIR)/compareCandidates.Tpo -c -o compareCandidates.o `test -f 'helperprograms/compareCandidates.c' || echo '$(srcdir)/'`helperprograms/compareCandidates.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/compareCandidates.Tpo $(DEPDIR)/compareCandidates.Po
#	$(AM_V_CC) \
#	source='helperprograms/compareCandidates.c' object='compareCandidates.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o compareCandidates.o `test -f 'helperprograms/compareCandidates.c' || echo '$(srcdir)/'`helperprograms/compareCandidates.c

compareCandidates.obj: helperprograms/compareCandidates.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT compareCandidates.obj -MD -MP -MF $(DEPDIR)/compareCandidates.Tpo -c -o compareCandidates.obj `if test -f 'helperprograms/compareCandidates.c'; then $(CYGPATH_W) 'helperprograms/compareCandidates.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/compareCandidates.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/compareCandidates.Tpo $(DEPDIR)/compareCandidates.Po
#	$(AM_V_CC) \
#	source='helperprograms/compareCandidates.c' object='compareCandidates.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o compareCandidates.obj `if test -f 'helperprograms/compareCandidates.c'; then $(CYGPATH_W) 'helperprograms/compareCandidates.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/compareCandidates.c'; fi`

skygridsetup.o: helperprograms/skygridsetup.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT skygridsetup.o -MD -MP -MF $(DEPDIR)/skygridsetup.Tpo -c -o skygridsetup.o `test -f 'helperprograms/skygridsetup.c' || echo '$(srcdir)/'`helperprograms/skygridsetup.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/skygridsetup.Tpo $(DEPDIR)/skygridsetup.Po
#	$(AM_V_CC) \
#	source='helperprograms/skygridsetup.c' object='skygridsetup.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o skygridsetup.o `test -f 'helperprograms/skygridsetup.c' || echo '$(srcdir)/'`helperprograms/skygridsetup.c

skygridsetup.obj: helperprograms/skygridsetup.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT skygridsetup.obj -MD -MP -MF $(DEPDIR)/skygridsetup.Tpo -c -o skygridsetup.obj `if test -f 'helperprograms/skygridsetup.c'; then $(CYGPATH_W) 'helperprograms/skygridsetup.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/skygridsetup.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/skygridsetup.Tpo $(DEPDIR)/skygridsetup.Po
#	$(AM_V_CC) \
#	source='helperprograms/skygridsetup.c' object='skygridsetup.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o skygridsetup.obj `if test -f 'helperprograms/skygridsetup.c'; then $(CYGPATH_W) 'helperprograms/skygridsetup.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/skygridsetup.c'; fi`

cmdline_skygridsetup.o: helperprograms/cmdline_skygridsetup.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT cmdline_skygridsetup.o -MD -MP -MF $(DEPDIR)/cmdline_skygridsetup.Tpo -c -o cmdline_skygridsetup.o `test -f 'helperprograms/cmdline_skygridsetup.c' || echo '$(srcdir)/'`helperprograms/cmdline_skygridsetup.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cmdline_skygridsetup.Tpo $(DEPDIR)/cmdline_skygridsetup.Po
#	$(AM_V_CC) \
#	source='helperprograms/cmdline_skygridsetup.c' object='cmdline_skygridsetup.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o cmdline_skygridsetup.o `test -f 'helperprograms/cmdline_skygridsetup.c' || echo '$(srcdir)/'`helperprograms/cmdline_skygridsetup.c

cmdline_skygridsetup.obj: helperprograms/cmdline_skygridsetup.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT cmdline_skygridsetup.obj -MD -MP -MF $(DEPDIR)/cmdline_skygridsetup.Tpo -c -o cmdline_skygridsetup.obj `if test -f 'helperprograms/cmdline_skygridsetup.c'; then $(CYGPATH_W) 'helperprograms/cmdline_skygridsetup.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/cmdline_skygridsetup.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cmdline_skygridsetup.Tpo $(DEPDIR)/cmdline_skygridsetup.Po
#	$(AM_V_CC) \
#	source='helperprograms/cmdline_skygridsetup.c' object='cmdline_skygridsetup.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o cmdline_skygridsetup.obj `if test -f 'helperprograms/cmdline_skygridsetup.c'; then $(CYGPATH_W) 'helperprograms/cmdline_skygridsetup.c'; else $(CYGPATH_W) '$(srcdir)/helperprograms/cmdline_skygridsetup.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool ctags distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS

vcsID:
	@cd $(top_builddir)/src/lalapps && $(MAKE) liblalapps.la

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
